apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent 
  template:
    metadata:
      labels:
        app: agent 
    spec:
      containers:
      - name: agent
        image: sejunee/client:latest
        command: ["/bin/sh"]
        args: ["-c", "/go/bin/agent"]
