apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent 
  template:
    metadata:
      labels:
        app: agent 
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: agent
        image: docker.io/sejunee/client:latest
        command: ["/bin/sh"]
        args: ["-c", "/go/bin/agent"]
