apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: control-server-hpa
spec:
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: control-server-deploy  
