apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-server-deploy
  labels:
    app: control-server-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: control-server
  template:
    metadata:
      labels:
        app: control-server
    spec:
      containers:
      - name: control-server
        image: docker.io/sejunee/server:latest
        command: ["/bin/sh"]
        args: ["-c", "/go/bin/echo"]
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "100m"
